let listaPlatos = [
    {
        imgPLato: "./img/desayuno01.jpg",
        precioPlato: 15.00,
        nombrePlato:"Desayuno de la Casa",
        descripcionPlato: "Huevos, pancakes y tocino",
        cantidad: 0,
        nombreCategoria: "Desayuno",
    },
    {
        imgPLato: "./img/ensalada01.jpg",
        precioPlato: 12.00,
        nombrePlato:"Ensalada César",
        descripcionPlato: "Con salsa ranch",
        cantidad: 0,
        nombreCategoria: "Ensalada",
    },
    {
        imgPLato: "./img/macarrones.jpg",
        precioPlato: 8.00,
        nombrePlato:"Macarrones con queso",
        descripcionPlato: "Queso parmesano",
        cantidad: 0,
        nombreCategoria: "Almuerzo, Cena",
    },
    {
        imgPLato: "./img/Hamburguesa.jpg",
        precioPlato: 9.00,
        nombrePlato:"Hamburguesa Clásica",
        descripcionPlato: "Con queso cheddar",
        cantidad: 0,
        nombreCategoria: "Almuerzo",
    },
    {
        imgPLato: "./img/pollo.jpg",
        precioPlato: 8.00,
        nombrePlato:"Pollo Asado",
        descripcionPlato: "Con papas fritas",
        cantidad: 0,
        nombreCategoria: "Almuerzo",
    },
    {
        imgPLato: "./img/pizza.jpg",
        precioPlato: 5.00,
        nombrePlato:"Pizza Margarita",
        descripcionPlato: "Tomate, mozzarella y albahaca",
        cantidad: 0,
        nombreCategoria: "Almuerzo",
    },
    {
        imgPLato: "./img/pescado.jpg",
        precioPlato: 20.00,
        nombrePlato:"Pescado a la plancha",
        descripcionPlato: "Pescado de temporada y verduras",
        cantidad: 0,
        nombreCategoria: "Cena",
    },

    {
        imgPLato: "./img/pieLimon.jpg",
        precioPlato: 5.00,
        nombrePlato:"Pie de Limón",
        descripcionPlato: "De la casa",
        cantidad: 0,
        nombreCategoria: "Postres",
    },{
        imgPLato: "./img/cheesecake.jpg",
        precioPlato: 5.00,
        nombrePlato:"Cheesecake",
        descripcionPlato: "Con frutos rojos",
        cantidad: 0,
        nombreCategoria: "Postres",
    },

    {
        imgPLato: "./img/vinoTinto.jpg",
        precioPlato: 3.50,
        nombrePlato:"Vino Tinto",
        descripcionPlato: "De la casa",
        cantidad: 0,
        nombreCategoria: "Bebidas",
    },
    {
        imgPLato: "./img/vinoBlanco.jpg",
        precioPlato: 3.50,
        nombrePlato:"Vino Blanco",
        descripcionPlato: "De la casa",
        cantidad: 0,
        nombreCategoria: "Bebidas",
    },
    {
        imgPLato: "./img/cerveza.jpg",
        precioPlato: 2.50,
        nombrePlato:"Cerveza",
        descripcionPlato: "De la casa",
        cantidad: 0,
        nombreCategoria: "Bebidas",
    },

]
let carritoDeCompra = [];